# Generated by Django 2.2.2 on 2019-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pumpkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pkg', models.CharField(max_length=255)),
                ('var', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('lowp', models.IntegerField()),
                ('highp', models.IntegerField()),
                ('size', models.CharField(choices=[('sml', 'Small'), ('med', 'Medium'), ('lge', 'Large'), ('jbo', 'Jambo'), ('xlge', 'XL'), ('med-lge', 'med-lge')], max_length=1)),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
    ]
