# Generated by Django 2.2.2 on 2019-06-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20190605_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pumpkin',
        ),
    ]
